In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7662e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7523, 0.4249, 0.0579],
        [0.9867, 0.3246, 0.0417],
        [0.2940, 0.8010, 0.5710],
        [0.2059, 0.6307, 0.8251],
        [0.6209, 0.9091, 0.8762]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [20]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

# x = x.new_ones(4,2, dtype=torch.long)
# print(x)                                     # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0468,  0.7260, -1.4544],
        [-1.9249, -0.3250,  0.8222],
        [-0.1134, -0.2040, -0.5993],
        [-0.4732, -0.1125,  0.1735],
        [-0.0458, -1.2448,  0.0556]])


Get its size:



In [18]:
print(x.size()[0]**x.size()[1])

16


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1013,  1.0570, -0.9263],
        [-1.3708,  0.1415,  1.3346],
        [ 0.7832,  0.6131,  0.1497],
        [ 0.0657,  0.3181,  0.2415],
        [ 0.3371, -1.0451,  0.1645]])


Addition: syntax 2



In [24]:
print(torch.add(x, y))

tensor([[ 0.1013,  1.0570, -0.9263],
        [-1.3708,  0.1415,  1.3346],
        [ 0.7832,  0.6131,  0.1497],
        [ 0.0657,  0.3181,  0.2415],
        [ 0.3371, -1.0451,  0.1645]])


Addition: providing an output tensor as argument



In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1013,  1.0570, -0.9263],
        [-1.3708,  0.1415,  1.3346],
        [ 0.7832,  0.6131,  0.1497],
        [ 0.0657,  0.3181,  0.2415],
        [ 0.3371, -1.0451,  0.1645]])


Addition: in-place



In [28]:
# adds x to y
y.add_(x)
print(y)

x.add_(y)
print(x)

tensor([[ 0.0546,  1.7829, -2.3807],
        [-3.2956, -0.1835,  2.1568],
        [ 0.6697,  0.4092, -0.4496],
        [-0.4075,  0.2057,  0.4150],
        [ 0.2913, -2.2899,  0.2201]])
tensor([[ 0.0078,  2.5089, -3.8351],
        [-5.2205, -0.5085,  2.9790],
        [ 0.5563,  0.2052, -1.0490],
        [-0.8807,  0.0932,  0.5885],
        [ 0.2455, -3.5348,  0.2757]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [29]:
print(x[:, 1])

tensor([ 2.5089, -0.5085,  0.2052,  0.0932, -3.5348])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1734])
1.1734299659729004


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [32]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [33]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [34]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.1734], device='cuda:0')
tensor([2.1734], dtype=torch.float64)
